services:
  ordersmicroservice.api:
    image: ordersmicroserviceapi
    build:
      context: .
      dockerfile: OrdersMicroservice.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_HOST=mongodb-container
      - MONGODB_PORT=27017
      - MONGODB_DATBASE=OrdersDatabase
      - UsersMicroserviceName=localhost
      - UsersMicroservicePort=9090
      - ProductsMicroserviceName=localhost
      - ProductsMicroservicePort=5201
    ports:
      - "8080:8080"
    networks:
      - orders-mongodb-network
  
  mongodb-container:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - ../mongo-init:/docker-entrypoint-initdb.d
    networks:
      - orders-mongodb-network

networks:
   orders-mongodb-network:
     driver: bridge  
